apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-console
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/2-services/openshift-console
    repoURL: https://github.com/ekleinso/microshift.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
