apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  k8s-app: minio
resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

